In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

In [2]:
train=pd.read_csv(r'C:\Users\satya\Jupyter\9-Machine Learning\house prediction dataset\train.csv')
test=pd.read_csv(r'C:\Users\satya\Jupyter\9-Machine Learning\house prediction dataset\test.csv')
X_train=train.iloc[:,:-1]
Y_train=train.iloc[:,-1]
X_test=test
train=None
test=None

In [3]:
print(X_train.shape,X_test.shape)

(1460, 80) (1459, 80)


In [4]:
columns=X_train.columns
columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

#### removing the columns which have more than half null values

In [5]:
for column in columns:
    if X_train[column].isnull().sum()/X_train.shape[0]>0.5:
        X_train.drop([column],inplace=True,axis=1)
        X_test.drop([column],inplace=True,axis=1)
X_train.drop(['FireplaceQu','Id'],axis=1,inplace=True)
X_test.drop(['FireplaceQu','Id'],axis=1,inplace=True)

In [6]:
X_train

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0             60       RL         65.0     8450   Pave      Reg         Lvl   
1             20       RL         80.0     9600   Pave      Reg         Lvl   
2             60       RL         68.0    11250   Pave      IR1         Lvl   
3             70       RL         60.0     9550   Pave      IR1         Lvl   
4             60       RL         84.0    14260   Pave      IR1         Lvl   
...          ...      ...          ...      ...    ...      ...         ...   
1455          60       RL         62.0     7917   Pave      Reg         Lvl   
1456          20       RL         85.0    13175   Pave      Reg         Lvl   
1457          70       RL         66.0     9042   Pave      Reg         Lvl   
1458          20       RL         68.0     9717   Pave      Reg         Lvl   
1459          20       RL         75.0     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... OpenPorchSF EnclosedPorch 3SsnPorch  \
0       AllPub    Inside       Gtl  ...          61             0         0   
1       AllPub       FR2       Gtl  ...           0             0         0   
2       AllPub    Inside       Gtl  ...          42             0         0   
3       AllPub    Corner       Gtl  ...          35           272         0   
4       AllPub       FR2       Gtl  ...          84             0         0   
...        ...       ...       ...  ...         ...           ...       ...   
1455    AllPub    Inside       Gtl  ...          40             0         0   
1456    AllPub    Inside       Gtl  ...           0             0         0   
1457    AllPub    Inside       Gtl  ...          60             0         0   
1458    AllPub    Inside       Gtl  ...           0           112         0   
1459    AllPub    Inside       Gtl  ...          68             0         0   

     ScreenPorch PoolArea  MiscVal  MoSold  YrSold  SaleType SaleCondition  
0              0        0        0       2    2008        WD        Normal  
1              0        0        0       5    2007        WD        Normal  
2              0        0        0       9    2008        WD        Normal  
3              0        0        0       2    2006        WD       Abnorml  
4              0        0        0      12    2008        WD        Normal  
...          ...      ...      ...     ...     ...       ...           ...  
1455           0        0        0       8    2007        WD        Normal  
1456           0        0        0       2    2010        WD        Normal  
1457           0        0     2500       5    2010        WD        Normal  
1458           0        0        0       4    2010        WD        Normal  
1459           0        0        0       6    2008        WD        Normal  

[1460 rows x 74 columns]

#### now converting the object type of data into numerical data

In [7]:
columns=X_train.columns
object_type_columns=[]
for i in range(columns.shape[0]):
    if X_train[columns[i]].dtype=='O':
        object_type_columns.append(i)
# object_type_columns

In [8]:
#converting object to numerical and filling nan values of object type columns
for i in object_type_columns:
    train_non_null_index=X_train.iloc[:,i][X_train.iloc[:,i].notnull()].index
    test_non_null_index=X_test.iloc[:,i][X_test.iloc[:,i].notnull()].index
    enc=OrdinalEncoder()
    X_train.iloc[train_non_null_index,i]=enc.fit_transform(X_train.iloc[train_non_null_index,i].values.reshape((-1,1)))
    X_test.iloc[test_non_null_index,i]=enc.transform(X_test.iloc[test_non_null_index,i].values.reshape((-1,1)))
    X_train.fillna({columns[i]:X_train.iloc[train_non_null_index,i].mean()},inplace=True)
    X_test.fillna({columns[i]:X_train.iloc[train_non_null_index,i].mean()},inplace=True)

In [9]:
#filling nan values of non object type columns
non_obj_type_columns=[i for i in range(X_train.columns.shape[0]) if i not in object_type_columns]
for i in non_obj_type_columns:
    X_train.fillna({X_train.columns[i]:X_train.iloc[:,i].mean()},inplace=True)
    X_test.fillna({X_train.columns[i]:X_train.iloc[:,i].mean()},inplace=True)

In [10]:
train=X_train.copy()
train['Price']=Y_train
corr=train.corr()


In [11]:
corr=pd.DataFrame(corr.iloc[:-1,-1].values,index=corr.index[:-1],columns=['Correlation'])
corr['Correlation']=np.abs(corr['Correlation'])

In [12]:
corr=corr.sort_values(by='Correlation',ascending=False)
corr

Correlation
OverallQual     0.790982
GrLivArea       0.708624
GarageCars      0.640409
ExterQual       0.636884
GarageArea      0.623431
...                  ...
MasVnrType      0.016731
LandContour     0.015453
Utilities       0.014314
BsmtFinSF2      0.011378
Condition2      0.007513

[74 rows x 1 columns]

In [13]:
corr_index=corr.index
corr_index

Index(['OverallQual', 'GrLivArea', 'GarageCars', 'ExterQual', 'GarageArea',
       'TotalBsmtSF', '1stFlrSF', 'BsmtQual', 'KitchenQual', 'FullBath',
       'TotRmsAbvGrd', 'YearBuilt', 'YearRemodAdd', 'GarageFinish',
       'MasVnrArea', 'GarageYrBlt', 'Fireplaces', 'HeatingQC', 'BsmtFinSF1',
       'Foundation', 'GarageType', 'LotFrontage', 'WoodDeckSF', '2ndFlrSF',
       'OpenPorchSF', 'HalfBath', 'BsmtExposure', 'LotArea', 'LotShape',
       'CentralAir', 'Electrical', 'PavedDrive', 'BsmtFullBath', 'RoofStyle',
       'BsmtUnfSF', 'SaleCondition', 'Neighborhood', 'HouseStyle',
       'BedroomAbvGr', 'MSZoning', 'GarageCond', 'KitchenAbvGr', 'RoofMatl',
       'EnclosedPorch', 'ExterCond', 'Functional', 'ScreenPorch', 'GarageQual',
       'Exterior2nd', 'Exterior1st', 'Heating', 'PoolArea', 'Condition1',
       'BldgType', 'MSSubClass', 'OverallCond', 'LotConfig', 'BsmtFinType1',
       'BsmtCond', 'SaleType', 'LandSlope', 'MoSold', '3SsnPorch', 'Street',
       'BsmtFinType2', 'YrS

In [14]:
print(X_train.shape,X_test.shape)

(1460, 74) (1459, 74)


In [15]:
from sklearn.ensemble import RandomForestRegressor

In [16]:
regressor=RandomForestRegressor(criterion='mse',max_depth=8,random_state=0)

In [17]:
regressor.fit(X_train.loc[:,corr_index],Y_train)

RandomForestRegressor(max_depth=8, random_state=0)

In [18]:
regressor.score(X_train.loc[:,corr_index],Y_train)

0.9656168021209466

In [19]:
predictions=regressor.predict(X_test.loc[:,corr_index])
predictions

array([124405.53670685, 152889.81048367, 173585.54225078, ...,
       148921.01371182, 116832.48099135, 225671.75148892])

In [20]:
submission=pd.read_csv(r'C:\Users\satya\Jupyter\9-Machine Learning\house prediction dataset\sample_submission.csv')
submission

Id      SalePrice
0     1461  169277.052498
1     1462  187758.393989
2     1463  183583.683570
3     1464  179317.477511
4     1465  150730.079977
...    ...            ...
1454  2915  167081.220949
1455  2916  164788.778231
1456  2917  219222.423400
1457  2918  184924.279659
1458  2919  187741.866657

[1459 rows x 2 columns]

In [21]:
submission['SalePrice']=predictions
submission.set_index('Id',inplace=True)

In [22]:
submission

SalePrice
Id                 
1461  124405.536707
1462  152889.810484
1463  173585.542251
1464  177265.188667
1465  204262.909185
...             ...
2915   86789.773260
2916   91042.187053
2917  148921.013712
2918  116832.480991
2919  225671.751489

[1459 rows x 1 columns]

#### now use gradient boosting algorithm

In [23]:
from sklearn.ensemble import GradientBoostingRegressor

In [29]:
gb=GradientBoostingRegressor(random_state=0,max_depth=3)
gb.fit(X_train,Y_train)
gb.score(X_train,Y_train)

0.9639961193700084

In [30]:
predictions_gb=gb.predict(X_test)
predictions_gb

array([124287.38876868, 162386.01510238, 174056.40198366, ...,
       159689.19695445, 118039.37041249, 234747.58925764])

In [31]:
submission_gb=submission.copy()
submission_gb['SalePrice']=predictions_gb
submission_gb

SalePrice
Id                 
1461  124287.388769
1462  162386.015102
1463  174056.401984
1464  179743.979823
1465  199551.962350
...             ...
2915   81486.054967
2916   80698.120047
2917  159689.196954
2918  118039.370412
2919  234747.589258

[1459 rows x 1 columns]

In [32]:
submission_gb.to_csv('house price prediction using gradient boosting.csv')

#### now use xgboost algo

In [34]:
import xgboost as xg

In [35]:
xgb_r = xg.XGBRegressor(objective ='reg:linear',
                  n_estimators = 10, seed = 123)

In [36]:
xgb_r.fit(X_train,Y_train)

[23:33:10] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/objective/regression_obj.cu:188: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=10, n_jobs=8,
             num_parallel_tree=1, objective='reg:linear', predictor='auto',
             random_state=123, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=123, subsample=1, tree_method='exact', validate_parameters=1,
             verbosity=None)

In [38]:
xgb_r.score(X_train,Y_train)

0.9654866225532805

In [39]:
predictions_xgb=xgb_r.predict(X_test)
predictions_xgb

array([120787.44, 138556.06, 174697.67, ..., 148428.06, 113975.58,
       213491.92], dtype=float32)

In [40]:
submission_xgb=submission.copy()
submission_xgb['SalePrice']=predictions_xgb
submission_xgb

SalePrice
Id                 
1461  120787.437500
1462  138556.062500
1463  174697.671875
1464  177660.750000
1465  176259.078125
...             ...
2915   84480.687500
2916   88506.320312
2917  148428.062500
2918  113975.578125
2919  213491.921875

[1459 rows x 1 columns]

In [41]:
submission_xgb.to_csv('house price prediction using xgboosting.csv')